language: go

go:
  - '1.9'
  - '1.10'
  - '1.11'
  - '1.12'

script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - "if [[ $TRAVIS_GO_VERSION == 1.12 ]]; then go get github.com/alecthomas/gometalinter; fi"
  - "if [[ $TRAVIS_GO_VERSION == 1.12 ]]; then gometalinter --install; fi"
  - "if [[ $TRAVIS_GO_VERSION == 1.12 ]]; then gometalinter; fi"

after_success:
  - bash <(curl -s https://codecov.io/bash)
